
Terminal command to create your ssh tunnel
ssh -N -L 9298:a100-4021:9298 slj9342@bigpurple.nyumc.org
Windows MobaXterm info
Forwarded port:same as remote port
Remote server: a100-4021
Remote port: 9298
SSH server: bigpurple.nyumc.org
SSH login: slj9342
SSH port: 22
Use a Browser on your local machine to go to:
localhost:9298/lab?token=  (prefix w/ https:// if using password)

[I 2025-04-25 10:49:16.265 ServerApp] Extension package jupyter_lsp took 0.2269s to import
[I 2025-04-25 10:49:16.782 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-04-25 10:49:16.785 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-04-25 10:49:16.789 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-04-25 10:49:16.792 ServerApp] notebook | extension was successfully linked.
[I 2025-04-25 10:49:22.648 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-04-25 10:49:22.784 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-04-25 10:49:22.786 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-04-25 10:49:22.790 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-04-25 10:49:22.796 LabApp] JupyterLab extension loaded from /gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyterlab
[I 2025-04-25 10:49:22.796 LabApp] JupyterLab application directory is /gpfs/data/oermannlab/users/slj9342/.local/share/jupyter/lab
[I 2025-04-25 10:49:22.797 LabApp] Extension Manager is 'pypi'.
[I 2025-04-25 10:49:23.208 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-04-25 10:49:23.211 ServerApp] notebook | extension was successfully loaded.
[I 2025-04-25 10:49:23.212 ServerApp] Serving notebooks from local directory: /gpfs/data/oermannlab/users/slj9342/dl4med_final_project
[I 2025-04-25 10:49:23.212 ServerApp] Jupyter Server 2.14.2 is running at:
[I 2025-04-25 10:49:23.212 ServerApp] http://a100-4021:9298/tree?token=36ea3cddf4a10dbba3e5867b770f2ab964e669d2b3857591
[I 2025-04-25 10:49:23.212 ServerApp]     http://127.0.0.1:9298/tree?token=36ea3cddf4a10dbba3e5867b770f2ab964e669d2b3857591
[I 2025-04-25 10:49:23.212 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2025-04-25 10:49:25.000 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///gpfs/data/oermannlab/users/slj9342/.local/share/jupyter/runtime/jpserver-990217-open.html
    Or copy and paste one of these URLs:
        http://a100-4021:9298/tree?token=36ea3cddf4a10dbba3e5867b770f2ab964e669d2b3857591
        http://127.0.0.1:9298/tree?token=36ea3cddf4a10dbba3e5867b770f2ab964e669d2b3857591
[I 2025-04-25 10:49:25.038 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2025-04-25 10:50:02.923 ServerApp] 404 GET /hub/api (@192.168.0.104) 60.78ms referer=None
[I 2025-04-25 10:50:02.925 ServerApp] 302 GET / (@192.168.0.104) 0.25ms
[I 2025-04-25 10:50:02.927 JupyterNotebookApp] 302 GET /tree? (@192.168.0.104) 0.33ms
[I 2025-04-25 10:50:10.106 ServerApp] User 7ad82bedce4549ed95f0bd81ad0af72e logged in.
[I 2025-04-25 10:50:10.107 ServerApp] 302 POST /login? (7ad82bedce4549ed95f0bd81ad0af72e@192.168.0.104) 1.00ms
[I 2025-04-25 10:50:18.863 ServerApp] Kernel started: 9d672828-b73d-4efb-a6b9-68d7c84f6d3e
[I 2025-04-25 10:50:34.656 ServerApp] Connecting to kernel 9d672828-b73d-4efb-a6b9-68d7c84f6d3e.
[I 2025-04-25 15:21:15.417 ServerApp] 302 GET / (@192.168.0.102) 0.31ms
[I 2025-04-25 15:21:15.697 JupyterNotebookApp] 302 GET /tree? (@192.168.0.102) 0.41ms
[W 2025-04-25 15:21:15.918 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:21:15.947 ServerApp] 403 GET /api/kernelspecs?1745608875913 (@192.168.0.102) 29.90ms referer=None
[W 2025-04-25 15:21:15.948 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:21:15.949 ServerApp] 403 GET /api/kernels?1745608875913 (@192.168.0.102) 0.91ms referer=None
[W 2025-04-25 15:21:15.949 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:21:15.949 ServerApp] 403 GET /api/sessions?1745608875918 (@192.168.0.102) 1.18ms referer=None
[W 2025-04-25 15:21:15.949 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:21:15.950 ServerApp] 403 GET /api/kernels?1745608875918 (@192.168.0.102) 1.43ms referer=None
[W 2025-04-25 15:21:15.959 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:21:15.960 ServerApp] 403 GET /api/kernelspecs?1745608875952 (@192.168.0.102) 0.44ms referer=None
[I 2025-04-25 15:21:15.960 ServerApp] 302 GET / (@192.168.0.102) 0.18ms
[I 2025-04-25 15:21:16.048 JupyterNotebookApp] 302 GET /tree? (@192.168.0.102) 0.27ms
[W 2025-04-25 15:21:16.157 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:21:16.157 ServerApp] 403 GET /api/kernelspecs?1745608876155 (@192.168.0.102) 0.49ms referer=None
[W 2025-04-25 15:21:16.159 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:21:16.159 ServerApp] 403 GET /api/kernels?1745608876155 (@192.168.0.102) 0.49ms referer=None
[W 2025-04-25 15:21:16.160 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:21:16.160 ServerApp] 403 GET /api/kernels?1745608876156 (@192.168.0.102) 0.45ms referer=None
[W 2025-04-25 15:21:16.160 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:21:16.160 ServerApp] 403 GET /api/sessions?1745608876157 (@192.168.0.102) 0.48ms referer=None
[W 2025-04-25 15:21:16.166 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:21:16.166 ServerApp] 403 GET /api/kernelspecs?1745608876160 (@192.168.0.102) 0.46ms referer=None
[W 2025-04-25 15:25:56.806 ServerApp] 404 GET /hub/api (@192.168.0.102) 1.44ms referer=None
[I 2025-04-25 15:25:56.808 ServerApp] 302 GET / (@192.168.0.102) 0.21ms
[I 2025-04-25 15:25:56.810 JupyterNotebookApp] 302 GET /tree? (@192.168.0.102) 0.28ms
[I 2025-04-25 15:26:04.810 ServerApp] User 5bfef4860b734ed6b67c8e2b6d0d18d3 logged in.
[I 2025-04-25 15:26:04.811 ServerApp] 302 POST /login? (5bfef4860b734ed6b67c8e2b6d0d18d3@192.168.0.102) 0.67ms
[I 2025-04-25 15:26:14.166 ServerApp] Kernel started: 4321761f-04e6-4b5d-9802-ceb9c3342fd7
[I 2025-04-25 15:26:21.918 ServerApp] Connecting to kernel 4321761f-04e6-4b5d-9802-ceb9c3342fd7.
[I 2025-04-25 15:26:22.314 ServerApp] 302 GET / (@192.168.0.102) 0.22ms
[I 2025-04-25 15:26:22.371 JupyterNotebookApp] 302 GET /tree? (@192.168.0.102) 0.33ms
[W 2025-04-25 15:26:22.441 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:26:22.441 ServerApp] 403 GET /api/kernelspecs?1745609182437 (@192.168.0.102) 0.56ms referer=None
[W 2025-04-25 15:26:22.449 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:26:22.449 ServerApp] 403 GET /api/kernels?1745609182438 (@192.168.0.102) 0.50ms referer=None
[W 2025-04-25 15:26:22.450 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:26:22.450 ServerApp] 403 GET /api/kernels?1745609182441 (@192.168.0.102) 0.45ms referer=None
[W 2025-04-25 15:26:22.450 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:26:22.450 ServerApp] 403 GET /api/sessions?1745609182442 (@192.168.0.102) 0.49ms referer=None
[I 2025-04-25 15:26:22.454 ServerApp] 302 GET / (@192.168.0.102) 0.34ms
[W 2025-04-25 15:26:22.455 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:26:22.455 ServerApp] 403 GET /api/kernelspecs?1745609182449 (@192.168.0.102) 0.62ms referer=None
[I 2025-04-25 15:26:22.457 JupyterNotebookApp] 302 GET /tree? (@192.168.0.102) 0.27ms
[W 2025-04-25 15:26:22.503 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:26:22.503 ServerApp] 403 GET /api/kernelspecs?1745609182501 (@192.168.0.102) 0.51ms referer=None
[W 2025-04-25 15:26:22.504 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:26:22.504 ServerApp] 403 GET /api/kernels?1745609182502 (@192.168.0.102) 0.51ms referer=None
[W 2025-04-25 15:26:22.508 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:26:22.508 ServerApp] 403 GET /api/kernels?1745609182504 (@192.168.0.102) 0.48ms referer=None
[W 2025-04-25 15:26:22.509 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:26:22.509 ServerApp] 403 GET /api/sessions?1745609182504 (@192.168.0.102) 0.46ms referer=None
[W 2025-04-25 15:26:22.509 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-25 15:26:22.509 ServerApp] 403 GET /api/kernelspecs?1745609182506 (@192.168.0.102) 0.50ms referer=None
[I 2025-04-25 15:28:29.584 ServerApp] Kernel interrupted: 4321761f-04e6-4b5d-9802-ceb9c3342fd7
[I 2025-04-25 15:47:13.912 ServerApp] Starting buffering for 9d672828-b73d-4efb-a6b9-68d7c84f6d3e:77c2f592-9dcf-4604-9208-df05bbb22b86
