
Terminal command to create your ssh tunnel
ssh -N -L 8769:a100-4015:8769 slj9342@bigpurple.nyumc.org
Windows MobaXterm info
Forwarded port:same as remote port
Remote server: a100-4015
Remote port: 8769
SSH server: bigpurple.nyumc.org
SSH login: slj9342
SSH port: 22
Use a Browser on your local machine to go to:
localhost:8769/lab?token=  (prefix w/ https:// if using password)

[I 2025-04-22 09:43:26.263 ServerApp] Extension package jupyter_lsp took 0.2174s to import
[I 2025-04-22 09:43:26.775 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-04-22 09:43:26.779 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-04-22 09:43:26.783 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-04-22 09:43:26.786 ServerApp] notebook | extension was successfully linked.
[I 2025-04-22 09:43:30.388 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-04-22 09:43:30.520 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-04-22 09:43:30.521 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-04-22 09:43:30.522 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-04-22 09:43:30.530 LabApp] JupyterLab extension loaded from /gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyterlab
[I 2025-04-22 09:43:30.530 LabApp] JupyterLab application directory is /gpfs/data/oermannlab/users/slj9342/.local/share/jupyter/lab
[I 2025-04-22 09:43:30.531 LabApp] Extension Manager is 'pypi'.
[I 2025-04-22 09:43:30.948 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-04-22 09:43:30.952 ServerApp] notebook | extension was successfully loaded.
[I 2025-04-22 09:43:30.952 ServerApp] Serving notebooks from local directory: /gpfs/data/oermannlab/users/slj9342/dl4med_final_project
[I 2025-04-22 09:43:30.952 ServerApp] Jupyter Server 2.14.2 is running at:
[I 2025-04-22 09:43:30.952 ServerApp] http://a100-4015:8769/tree?token=361a7ba6b3f44279146afb1427f7fbd642579918f8fd4032
[I 2025-04-22 09:43:30.952 ServerApp]     http://127.0.0.1:8769/tree?token=361a7ba6b3f44279146afb1427f7fbd642579918f8fd4032
[I 2025-04-22 09:43:30.952 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2025-04-22 09:43:30.957 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///gpfs/data/oermannlab/users/slj9342/.local/share/jupyter/runtime/jpserver-1459252-open.html
    Or copy and paste one of these URLs:
        http://a100-4015:8769/tree?token=361a7ba6b3f44279146afb1427f7fbd642579918f8fd4032
        http://127.0.0.1:8769/tree?token=361a7ba6b3f44279146afb1427f7fbd642579918f8fd4032
[I 2025-04-22 09:43:30.986 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2025-04-22 09:43:42.426 ServerApp] 404 GET /hub/api (@192.168.0.103) 87.37ms referer=None
[I 2025-04-22 09:43:42.429 ServerApp] 302 GET / (@192.168.0.103) 0.27ms
[I 2025-04-22 09:43:42.431 JupyterNotebookApp] 302 GET /tree? (@192.168.0.103) 0.33ms
[I 2025-04-22 09:43:51.862 ServerApp] User a8519d339c974c5f9d5fcf053dab62cc logged in.
[I 2025-04-22 09:43:51.863 ServerApp] 302 POST /login? (a8519d339c974c5f9d5fcf053dab62cc@192.168.0.103) 1.14ms
[I 2025-04-22 09:44:19.556 ServerApp] Kernel started: a2de3573-04dc-416c-8de0-05b3c8ea776d
[I 2025-04-22 09:44:27.857 ServerApp] Connecting to kernel a2de3573-04dc-416c-8de0-05b3c8ea776d.
[I 2025-04-22 12:10:18.067 ServerApp] Kernel interrupted: a2de3573-04dc-416c-8de0-05b3c8ea776d
[I 2025-04-22 12:10:34.208 ServerApp] Kernel restarted: a2de3573-04dc-416c-8de0-05b3c8ea776d
[I 2025-04-22 12:10:34.214 ServerApp] Starting buffering for a2de3573-04dc-416c-8de0-05b3c8ea776d:fb2e8e5c-d77b-4b4b-8af5-e5b7e91305b1
[I 2025-04-22 12:10:34.221 ServerApp] Connecting to kernel a2de3573-04dc-416c-8de0-05b3c8ea776d.
[I 2025-04-22 12:10:34.222 ServerApp] Restoring connection for a2de3573-04dc-416c-8de0-05b3c8ea776d:fb2e8e5c-d77b-4b4b-8af5-e5b7e91305b1
[W 2025-04-22 12:10:38.731 ServerApp] Nudge: attempt 10 on kernel a2de3573-04dc-416c-8de0-05b3c8ea776d
[W 2025-04-22 12:10:43.742 ServerApp] Nudge: attempt 20 on kernel a2de3573-04dc-416c-8de0-05b3c8ea776d
[I 2025-04-22 13:38:15.591 ServerApp] Starting buffering for a2de3573-04dc-416c-8de0-05b3c8ea776d:fb2e8e5c-d77b-4b4b-8af5-e5b7e91305b1
[I 2025-04-22 13:40:17.832 ServerApp] 302 GET / (@192.168.0.104) 0.34ms
[I 2025-04-22 13:40:18.757 JupyterNotebookApp] 302 GET /tree? (@192.168.0.104) 0.52ms
[W 2025-04-22 13:40:24.770 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 13:40:24.799 ServerApp] 403 GET /api/kernelspecs?1745343624767 (@192.168.0.104) 29.72ms referer=None
[W 2025-04-22 13:40:24.991 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 13:40:24.992 ServerApp] 403 GET /api/kernels?1745343624767 (@192.168.0.104) 0.59ms referer=None
[W 2025-04-22 13:40:24.992 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 13:40:24.992 ServerApp] 403 GET /api/kernels?1745343624887 (@192.168.0.104) 0.60ms referer=None
[W 2025-04-22 13:40:24.993 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 13:40:24.993 ServerApp] 403 GET /api/sessions?1745343624888 (@192.168.0.104) 0.87ms referer=None
[W 2025-04-22 13:40:25.052 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 13:40:25.052 ServerApp] 403 GET /api/kernelspecs?1745343624972 (@192.168.0.104) 0.73ms referer=None
[I 2025-04-22 13:40:25.796 ServerApp] 302 GET / (@192.168.0.104) 0.21ms
[I 2025-04-22 13:40:25.956 JupyterNotebookApp] 302 GET /tree? (@192.168.0.104) 0.28ms
[W 2025-04-22 13:40:28.137 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 13:40:28.138 ServerApp] 403 GET /api/kernelspecs?1745343628134 (@192.168.0.104) 1.01ms referer=None
[W 2025-04-22 13:40:28.141 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 13:40:28.141 ServerApp] 403 GET /api/kernels?1745343628135 (@192.168.0.104) 0.48ms referer=None
[W 2025-04-22 13:40:28.142 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 13:40:28.142 ServerApp] 403 GET /api/kernels?1745343628137 (@192.168.0.104) 0.58ms referer=None
[W 2025-04-22 13:40:28.142 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 13:40:28.142 ServerApp] 403 GET /api/sessions?1745343628138 (@192.168.0.104) 0.86ms referer=None
[W 2025-04-22 13:40:28.161 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/gpfs/data/oermannlab/users/slj9342/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 13:40:28.161 ServerApp] 403 GET /api/kernelspecs?1745343628143 (@192.168.0.104) 0.74ms referer=None
[W 2025-04-22 14:02:41.794 ServerApp] 404 GET /hub/api (@192.168.0.104) 2.36ms referer=None
[I 2025-04-22 14:02:41.796 ServerApp] 302 GET / (@192.168.0.104) 0.26ms
[I 2025-04-22 14:02:41.799 JupyterNotebookApp] 302 GET /tree? (@192.168.0.104) 0.29ms
[I 2025-04-22 14:02:47.579 ServerApp] User 49d87c7617694e5eb3b20f24a449af12 logged in.
[I 2025-04-22 14:02:47.594 ServerApp] 302 POST /login? (49d87c7617694e5eb3b20f24a449af12@192.168.0.104) 17.17ms
[I 2025-04-22 14:02:53.379 ServerApp] Connecting to kernel a2de3573-04dc-416c-8de0-05b3c8ea776d.
[I 2025-04-22 14:02:53.537 ServerApp] 302 GET / (@192.168.0.104) 0.24ms
[I 2025-04-22 14:02:53.616 JupyterNotebookApp] 302 GET /tree? (@192.168.0.104) 0.29ms
[I 2025-04-22 14:02:56.807 ServerApp] User 82b0b0bfd1824006bde87c29de4bf7c5 logged in.
[I 2025-04-22 14:02:56.808 ServerApp] 302 POST /login? (82b0b0bfd1824006bde87c29de4bf7c5@192.168.0.104) 0.70ms
[W 2025-04-22 14:02:58.952 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@192.168.0.104) 1.12ms referer=None
[W 2025-04-22 14:02:58.952 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@192.168.0.104) 1.43ms referer=None
slurmstepd-a100-4015: error: *** JOB 63191664 ON a100-4015 CANCELLED AT 2025-04-22T17:18:59 ***
